### ISSUE TITLE
High Disk Usage

### ISSUE THREAD

**Issue by dannymichel** [animosity22/homescripts#102]
You don't have a 'discussion' section or anything like that here, so i'm just opening an 'issue'.
I want to maybe do what you're doing now and not use mergerfs and just have radarr/sonarr copy instead of hardlinking, but i do a lot of downloading and i'm afraid that instead of once every 2 hours how i have it set up now to upload gdrive that the constant copying that radarr/sonarr do and the constant uploading that rclone will be doing will be heavy on resources.
The way i see it now, i have like 20-30 minutes of uploading time every 2 hours now on a schedule and the hardlinking instead of copying is less disc usage.
I use 'jellyfin' right now and it's very sensitive beta software. Any high disc or network activity basically upsets jellyfin and it refuses to work, so i have to be conscious of that.

How has it been for you?
Was mergerfs,  the upload schedule, and the hardlinking from radarr/sonarr days less resource intensive on your disc(s) and network/upload?

**Comment by animosity22** [comment]
So my theory is if I can simplify things, I try to remove layers if possible.

When I first built my stuff, I was limited on disk space so I used mergerfs to reduce that issue.

Since then, I just grabbed a nice 10TB seed disk that is used for that and it copies over to my TV/Movie Cache disks 1TB/2TB respectively which are SSDs. I landed on an hour as that was a good mix of waiting for things to settle and not upload over and over. I've got gigabit FIOS with no metering so I just let things go.

I've had zero issues since I switched over.

The only thing mergerfs really adds to the mix is hardlinking as my torrent area was shared with my upload area so it was not double counted.

The cons to my setup would be I use SSDs and they will wear out, but based on my use, that isn't going to happen for a number of years so at that point, they'll get replaced anyway with whatever the newer technology is.

Best advice is used whatever works best for how you want things to flow. I'm very tuned to my use case and my specific needs.

**Comment by dannymichel** [comment]
Yeah I hear you. I'm probably gonna stick with mergerfs but I'm always gonna have that feeling in the back of my head that removing that layer will somehow make things 'faster' or 'cleaner'

**Comment by animosity22** [comment]
Cleaner maybe, but the faster bit is not something I've ever been able to quantify or notice in any testing I've ever done. Adding a layer always add some slowdown, but I've not been able to actually measure it / notice it.

**Comment by animosity22** [comment]
Anything else, let me know. Issues are fine / rclone forums are fine. I really don't mind answering anything.
