### ISSUE TITLE
Cache and VFS Questions

### ISSUE THREAD

**Issue by peewee5** [animosity22/homescripts#2]
Just wanted to start out by saying that your configs and settings have helped immensely in trying to tweak my system.  I'm currently running a cache/crypt setup:

```
rclone mount sotcrypt: /media \
--allow-other \
--dir-cache-time 24h \
--cache-total-chunk-size 5G \
--cache-chunk-path /path/to/chunk \
--cache-chunk-size 10M \
--cache-tmp-upload-path /path/to/cache \
--cache-tmp-wait-time 60m \
--cache-info-age 36h \
--cache-db-path /path/to/cache \
--cache-workers 5 \
--buffer-size 100M \
--log-file /path/to/log \
--log-level INFO
```

With these settings, I still get buffering higher bitrate 4K movies and occasional failures to play the first or second time around with any movie.  Movies take anywhere from 10-20s to load.  Is there something that I can do to  speed that up and/or fix the 4K issue or is VFS the way to go?  

Secondly, with the upload script you have do you just hold everything that you download for the day on local storage using your rclone mount as read-only essentially and do you just have Radarr/Sonarr do the media management on the local disk before the nightly upload?  

Thanks again for all of you help, this is really awesome work you've done here.

**Comment by animosity22** [comment]
I found that the cache setup just didn't perform well enough for me so I have been using the vfs-read-chunk-size options now for quite some time with streaming a lot of stuff.

Are you playing directly from the mount? The buffer-size 100M should be 0M as the cache handles that by itself. I'd probably just move to VFS and see if that works for you.

For the second item, yes, I just keep a local storage area that I combine with rclone via mergerfs to display a single mount for my /gmedia that for Sonarr/Radarr/rTorrent/Plex/etc so no paths change for any application and nothing is lost in using Sonarr/Radarr and having it create hard links instead of copies for stuff as well.

**Comment by peewee5** [comment]
So I just moved everything over to the VFS/mergerfs setup.  I suppose these are my next questions.  Is the purpose of keeping everything staged locally before a nightly upload to prevent rate limiting?  Do you have Sonarr/Radarr do all of your Media Management locally and then just upload to gdrive at the end of the day?

**Comment by peewee5** [comment]
Also, am I to correct in understanding that after everything has been uploaded you are playing your media directly from your mount too?

**Comment by animosity22** [comment]
I stage every night just for each of use as I don't get more than 750GB these days anymore.

It allows me to use mergerfs and hard linking to copy files from my torrents and to my mount.

I do not play directly from rclone, but from my mergerfs mount.

/gmedia is my overall mount that used for Sonarr/Radarr/Plex/rTorrent/everything :)

Since my /data/local is on the same disk as my torrents, mergerfs hard links properly and when a new movie comes, it's available immediately without any extra copies.

Each night, I clear out my local but I have 6TB staging so I could wait a lot longer.

Hope that helps!

**Comment by peewee5** [comment]
Sorry, to re-open this but I had one additional question about your upload script.  Is the lockfile that you create in the script what allows you to run another rclone command while you have GD mounted? Also, do you notice a performance difference in your video files being read by Plex are in individual folders or all in the same folder?  Thanks again.

**Comment by animosity22** [comment]
The general limit for Google API his is ~10 per second based on the default quotas.

I use my own API key and I'm only running the single mount. 

There is no caching of any cloud data at all using just the VFS backend. The data is discarded after the file is closed. 

I have no use case for me of keeping anything local.

The gmedia.find.service just primes the cache. It is not required and just something I use as I don't mind consuming a few API hits on startup to have a cache of the  directory/file structure.

Yes, you can jump the dir-cache-time to be as high as you want and no real downside. I just picked that number and in reality, it could be a week or two weeks.

When you say rate limiting, those are 403 rate limit messages? Those can happen and when if you check my upload script, I mitigate that but using very few transfers/checkers.

```
/usr/bin/rclone move /data/local/ gcrypt: -P --checkers 3 --log-file /home/felix/logs/upload.log -v --tpslimit 3 --transfers 3 --drive-chunk-size 32M --exclude-from /home/felix/scripts/excludes --delete-empty-src-dirs

```

**Comment by RaymondSchnyder** [comment]
@animosity22 the joke is, i use even stricter limits in my upload script than you, and i still got rate limited...
(1 transfer at a time, bwlimit=15MB, 1tps..)

**Comment by RaymondSchnyder** [comment]
@animosity22 Yes i do use my own credentials.
Also at the moment, i have the weird problem that the mergefs mount "hangs" itself after a while.
strace ls /mnt/data says it hangs at stat("/mnt/data",

**Comment by RaymondSchnyder** [comment]
@animosity22 the joke is, i use even stricter limits in my upload script than you, and i still got rate limited...
(1 transfer at a time, bwlimit=15MB, 1tps..)

**Comment by RaymondSchnyder** [comment]
Had the VFS cache working for a few days, turned of radarr, sonarr and every other searching application before i got it working.
Yesterday i tried to turn them on.
Rclone VFS crashed, API limit instantly gone.

**Comment by animosity22** [comment]
What do you mean API limit gone? I'm not following what that is.

I have analyze turned off in both Sonarr and Radarr.

![image](https://user-images.githubusercontent.com/5088712/50092839-126c5300-01dd-11e9-8590-b05e9daafd90.png)

**Comment by animosity22** [comment]
It's not possibly to hit the daily API limit in a few minutes because of the other limits they have setup. You'd get 403 rate limit errors to slow down.

The quota/limits are listed in the API console.

![image](https://user-images.githubusercontent.com/5088712/50113689-ad325500-0210-11e9-84d4-c07bd35aa094.png)

**Comment by animosity22** [comment]
If you'd like, it's probably better to post on the rclone forums as this closed issue won't get a lot of other folks looking at it.

Share you config and I'm sure other folks can help out as well.

**Comment by RaymondSchnyder** [comment]
@animosity22 Just to reply, i will post on the forums later:
The limit i hit is the "per 100s per user"

**Comment by Dulanic** [comment]
Have you ever reconsidered this? Not sure if rclone improved it, but it works as good or better for me. Primarily because I use btrfs, and reflinks dont function properly /w mergerfs for me. I just use these options and it works fantastic. cache-tmp-wait-time helps prevent issues /w uploads for unpacks etc... since i use unpackerr.

```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/dulanic/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount decrypt:Media /mnt/gd \
--allow-other \
--attr-timeout 1000h \
--buffer-size 512M \
--dir-cache-time 1000h \
--no-modtime \
--log-level INFO \
--vfs-cache-mode full \
--cache-tmp-upload-path /mnt/btrfs/rclone \
--cache-dir=/mnt/btrfs/rclone/cache \
--vfs-cache-max-size 100G \
--cache-tmp-wait-time 60m \
--poll-interval 15s \
--log-file /var/log/rclone.log \
--timeout 1h \
--umask 022
ExecStop=/usr/bin/fusermount -uz /mnt/gd
Restart=on-failure
User=dulanic
Group=dulanic

[Install]
WantedBy=multi-user.target
```

**Comment by animosity22** [comment]
I use what's best for me :)

I don't use the cache backend as it's deprecated and have no API issues.

**Comment by Dulanic** [comment]
I meant in lieu of mergerfs for uploads :) Totally get you use whats best for you, i meant for the uploads. Guess this issue wasnt for that LOL I just searched for prior tickets around that.

**Comment by animosity22** [comment]
Why would I change out mergerfs as it works perfectly?

**Comment by Dulanic** [comment]
Additional overhead? No worries, keep it if you wish. Just feel is ismore efficient. The reason I do it is because mergerfs is due to the fact that mergerfs has issues doing hard links across devices for drive pools (I use BTRFS). With mergerfs I couldn't get hardlinks to function in sonarr/radarr and it would do full copies. Without mergerfs, the hardlinks work great.
