### ISSUE TITLE
Seeding?

### ISSUE THREAD

**Issue by hongkongkiwi** [animosity22/homescripts#28]
How do you handle seeding in your setup? Do you seed directly off gmedia?

Also, I wonder why you havn't made gmedia read_only in your setup.

Also wondering why you have the qbit_bad script, what problem does this solve?

**Comment by animosity22** [comment]
Yes, /gmedia a mergerfs mount comprised of a local disk and my Google Drive mount. Any seeding happens indirectly from the local disk underneath the mergerfs mount as I do not seed from my Google Drive.

I don't use /gmedia read only as I want the ability to delete things like upgrading media and also all my writes happen on /gmedia. I think you might my /GD which is my Google Rclone mount. That is read/write so I can delete and upgrade media.

The qbit_bad removes unregistered torrents from qbit via the API so I don't have to login and do it myself as my goal is as hands off as possible in my automated setup. I don't want to manage anything I don't have to.

**Comment by animosity22** [comment]
Let me know if you have any other questions.

**Comment by mouzzampk2014** [comment]
Hi @animosity22 thank you so much for great documentation. Literally took me few minutes to follow up and understand your setup. I have similar query as above, because torrent client is directly seeding from gmedia so basically its hardlink. I only have 250GB SSD so if I have 750GB torrents in queue in downloads folder and uploading 1 by 1 into cloud media folder that means it will also occupy space locally for seeding in downloads folder? Thank you

**Comment by mkeguy106** [comment]
Seeding from gdrive is a bad idea imho.  That's a lot of api calls.

**Comment by mouzzampk2014** [comment]
> Seeding from gdrive is a bad idea imho. That's a lot of api calls.

Completely make sense. I was just curious, so that means it's basically not hardlink as local is also occupying the space.
