### ISSUE TITLE
Concurrent Stream Limits?

### ISSUE THREAD

**Issue by shawnp0wers** [animosity22/homescripts#35]
My apologies if this was discussed before, I couldn't find the information in my admittedly cursory searching.

Is there an upper limit regarding the number of concurrent streams being served directly from GD? Apart from bandwidth, obviously. There is, as I'm sure is true with everyone, a massive uptick in the number of friends who are streaming from my Plex server. I'm also just about out of local storage.

I've set up a test server, and while there is a bit longer start time with each stream, it seems to function well streaming directly from GD (duh, that's what everyone here is doing) -- but how well does it scale? Does anyone have any realworld experience with 6-12 streams at once?

**Comment by animosity22** [comment]
I'm 8 max that I've seen so far as I have small setup compared to some.

Scaling would be done via more rclone mounts if you found that rclone was a bottleneck. 

It really depends on the bottleneck as you scaled up as I think you can scale without too much of an issue from rclone.

I'd expect your bandwidth and CPU to be more the problem in what I've seen.

You can always ask on the https://forums.rclone.org as I've had some people mention some crazy high number of streams and bandwidth.

The other thing to think about is your backend. Google limits to 10TB down a month so that might be a factor as well.

**Comment by shawnp0wers** [comment]
Ahh, interesting. I had a hard time finding the actual limits Google puts on GD. I know the 700 (750?) GB per day upload, and there's an API call issue, but I didn't know about the 10TB monthly download.

You've obviously not my google, so I can dig more, but I'm curious if that is per user? If I pay for 5 users a month for my gsuite (in order to "officially" get unlimited storage) I could some how split my library up, or share the data internally to my 5 user accounts.

Ok, feel free to tell me to sod off and search for myself, but if I have multiple users in my gsuite account, can they share a single chunk of data, and have 5 separate rclone instances access the data via 5 different accounts (hopefully increasing monthly downloads)? I'm not sure if rclone can access "shared with me" data in a google drive... I'd hate to upload the same data 5 times, what a waste that would be.

**Comment by animosity22** [comment]
Sorry asI must have missed it.

Currently, they do not enforce the 5 user rule so 1 user is all you need on a GSuite. To my understanding, the limits for download/upload are per user but I'm not an expert in that area as I don't tend to hit those limits.

Shared with me works fine with rclone as well as you'd make a separate remote for it as you can only see shared-with-me or not.

**Comment by animosity22** [comment]
Let me know if you have any other questions!
