### ISSUE TITLE
BTRFS impact ?

### ISSUE THREAD

**Issue by WoisWoi** [animosity22/homescripts#96]
Hi,

You said you "found a huge performance improvement" to use BTRFS over EXT4/XFS, could you provide more details please? :)
How is the improvement manifested in your use and how important is it? Does it impact more Plex or Radarr/Sonarr?

Thanks you

**Comment by animosity22** [comment]
I use a couple things in my setup and when I copy / backup to other spots, I see a 70-80% speed improvement in copying my data.

Directory listings are also insanely fast for my plex folder.

```
felix@gemini:/opt/docker/data/plex$ time du -sh *
0	custom-cont-init.d
0	custom-services.d
54G	Library

real	0m4.034s
user	0m0.263s
sys	0m2.487s
```

I don't have any EXT4 to test against or show, but for me, it was a much better overall improvement in my setup.  I'd say test it out and see how it works for you.

XFS doesn't do as well with small files which is the plex data. 

I'd imagine you'd see some benefit with XFS with Sonarr/Radarr since it does better with generally larger files, but I really haven't done much testing with XFS.

Hope that helps!
